%YAML 1.1
---
version: '>=0.0.0 || @head'
export: |

    project "GainInput"

        kind "StaticLib"

        files "lib/source/**"

        zpm.export [[
            includedirs "lib/include"

            cppdialect "C++11"

            filter "system:windows"
                links "xinput"
            filter {}
        ]]
...