%YAML 1.1
---
version: '>=0.0.0 || @head'
export: |

    project "GainInput"

        kind "StaticLib"

        files "lib/source/**"
        
        filter "system:not ios"
            removefiles "lib/source/**Ios.mm"
        
        filter "system:not macosx"
            removefiles "lib/source/**Mac.mm"
        filter {}

        zpm.export [[
            includedirs "lib/include"

            cppdialect "C++11"

            defines "GAINPUT_LIB_BUILD"

            filter "system:windows"
                links "xinput"

            filter "system:linux"
                links "x11"
            filter {}
        ]]
...